# For builds using the debug probe.
# [target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip RP2040"

# For release builds not using the debug probe. To flash directly to the chip.
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "picotool load --update --verify --execute -t elf"

[build]
target = "thumbv8m.main-none-eabihf" # RP2350 / Pico 2 (Cortex-M33)
# target = "thumbv6m-none-eabi"        # RP2040 / Pico W (Cortex-M0+)

[env]
DEFMT_LOG = "debug"
