# For builds using the debug probe.
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040"

# For release builds note using the debug probe. To flash directly to the chip.
# [target.thumbv6m-none-eabi]
# runner = "elf2uf2-rs -d"

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
